controller_joint_names: ['', 'Proximal_Joint_1', 'Distal_Joint_1', 'Platform_Joint_1', 'Proximal_Joint_2', 'Distal_Joint_2', 'Platform_Joint_2', 'Proximal_Joint_3', 'Distal_Joint_3', 'Platform_Joint_3', ]
